[package]
name = "learningRust"
version = "0.1.0"
authors = ["enjay27 <kdkm2002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
